### PR TITLE
envydis: add full documentation of BAR on GK110

### PR DESCRIPTION
**Pull request by hakzsam**

### CODE REVIEW

**Comment by imirkin** [comment]
Seems fine to me... if you're confident about such stuff, feel free to just push rather than go to the trouble of making PR's and whatnot.

**Comment by enotdetcelfer** [comment]
Speaking of documentation... I'm really interested in the project and
how/if it could be used with something like BareMetal OS... but I'm
struggling to find a good primer on what you guys have been up to. Is there
any overall documentation or guide for envy tools that I've been missing?
Should I just start scouring code/comments? Everything I've found online is
missing stuff or just the basic description on github.

Sorry if this isn't the place for this... I tried to find a forum to ask
questions through the github page but couldn't find it. Thx

**Comment by imirkin** [comment]
http://envytools.rtfd.org

if you have concrete questions, try #nouveau on freenode.

**Comment by enotdetcelfer** [comment]
Awesome Thanks!

**Pull request merged**
