### PR TITLE
add cupti_trace, a new tool for REing performance counters

### PR DESCRIPTION
**Pull request by hakzsam**
No problems with licences/copyrights this time. :-)

### CODE REVIEW

**Comment by mupuf** [comment]
It would be nice to say what you changed :)

**Comment by hakzsam** [comment]
I removed all the code without a licence. :)

**Comment by hakzsam** [comment]
In this version, I directly use binaries instead of using the cupti API. This is probably bad for performance, but it's a tool for REing.. not a big issue in my opinion.
I also added a copyright+licence as requested by joi on IRC.

**Comment by mupuf** [comment]
The tool has made some wonderful traces, let's merge it now that there is no code from nvidia anymore.

**Pull request merged**
