### PR TITLE
envyas: Document the command line for envyas

### PR DESCRIPTION
**Pull request by Echelon9**
Includes documentation that will make its way to readthedocs

### CODE REVIEW

**Comment by koriakin** [comment]
docs/envyas/index.rst is mostly duplicated from envydis docs - IMO it'd be better to have a merged doc for them, marking options specific to envydis or envyas.

**Comment by Echelon9** [comment]
OK, I'll rework this new documentation as an addition to the existing `envydis` documentation.

**Comment by Echelon9** [comment]
@koriakin I've modified the docs to roll envydis and envyas in together, and rebased this PR. Ready to be merged.

**Comment by Echelon9** [comment]
As discussed with @pierremoreau on IRC, I have added a reference in the two C files to docs/envydis/index.rst for ISA details.

**Pull request merged**
