### PR TITLE
Portability improvements

### PR DESCRIPTION
**Pull request by saper**
cgen needs to be built with -fPIC

autodetect X11 header location (for systems with /usr/local/include/X11 ...)

Use POSIX basename(3) semantics, where the argument can be modified

### CODE REVIEW

**Comment by mupuf** [comment]
Ah ah, another Marcin contributing to envytools :D The joke that one has to be called Martin/Maarten/Marcin to contribute lives on!

Anyway, back to your contributions. I don't have much to say about the code as it looks pretty sane, but the commit messages do need some improvements:

 * Use POSIX basename(3):
   * Suggested title: "demmt: use POSIX basename(3)"
   * Add an explanation what's wrong with the GNU version. Is it because you are trying to build envytools on musl?
* Autodetect X11 header location:
  * Suggested title: "cmake: autodetect X11 header location"
  * Add the list of platforms that start working when doing that.
* cgen: nva needs position independent code:
  * Please explain what platforms benefit from this, and **WHY**
  
 Thanks, Marcin!

**Comment by saper** [comment]
Thank you Mar[tc]in :)

I personally do not like to sprinkle git commit messages with compiler output, but you are right, it is hard to understand why those changes were needed for me.

**Comment by saper** [comment]
The `-fPIC` error isn't really OS specific, I wonder why it does not appear on other platforms (maybe somehow we default to position independent code anyway).

**Comment by saper** [comment]
Are there any files available somewhere to check if this does not break `demmt` option parsing?

**Comment by mupuf** [comment]
Thanks for updating the series!

I'll try compiling it on my machine to check if didn't break the Linux build, and if we don't more more developer feedback soon, I'll just merge it.

> Are there any files available somewhere to check if this does not break demmt option parsing?

Not that I am aware of.

**Pull request merged**
