### PR TITLE
rnndb/graph: cosmetic changes to maxwell texture header definitons

### PR DESCRIPTION
**Pull request by ghost**
Modified to make headergen prefix the definitions with the chipset name,
as is done with the G80 headers.

Also renamed from gm200 to gm107, as that's where the functionality
actually appeared.

### CODE REVIEW

**Comment by imirkin** [comment]
Please also fix demmt/main.c

**Comment by skeggsb** [comment]
What needs fixing there?

**Comment by imirkin** [comment]
Filename

**Comment by imirkin** [comment]
Looks fine now, thanks!

**Comment by hakzsam** [comment]
I think this should be merged, Ben? :-)

**Pull request closed without merging**
