### PR TITLE
envydis: add BAR insn for GM107

### PR DESCRIPTION
**Pull request by hakzsam**

### CODE REVIEW

**Comment by imirkin** [comment]
Did you mean 9f? The 2 bit is set in a few cases...

**Comment by hakzsam** [comment]
err, what?
I don't where the bit 2 is set.

**Comment by imirkin** [comment]
Don't mind me. b != d. It's the 4 bit you're missing in that mask, and it's never used, so ... all good.

**Comment by hakzsam** [comment]
Okay. :-)
I updated the PR for BAR on GK110 if you want to have a look.
And I also submitted patches for that on mesa-dev.

**Pull request merged**
